// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elzloqcldhgcnvxkblzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsemxvcWNsZGhnY252eGtibHpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzOTEwMTEsImV4cCI6MjA2OTk2NzAxMX0.c3_fURt8jvBQLiuZy_yUcIjW2iY_bHqxcmHudMD-qLc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});